profile: cover.out
threshold:
  file: 70
  package: 80
  total: 90
override:
  - path: ^pkg/lib/foo$
    threshold: 100

exclude:
  paths:
    - \.pb\.go$
    - ^pkg/bar
breakdown-file-name: ''

diff:
  base-breakdown-file-name: ''
  threshold: null