name: Go Coverage Badge

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25.0

    - name: Install dependencies
      run: go mod download

    - name: Run Tests and generate coverage report
      run: go test ./... -covermode=count -coverprofile=coverage.out

    - name: Install gocover-covertura
      run: go install github.com/tebeka/go-cobertura@latest

    - name: Convert Go Coverage to Cobertura XML
      run: go-cobertura -infile=coverage.out -outfile=coverage.xml

    - name: Generate Go Coverage Badge
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true