name: Go Coverage Badge

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25.0

    - name: Install dependencies
      run: go mod download

    - name: Run Tests and generate coverage report
      run: go test ./... -covermode=count -coverprofile=coverage.out

    - name: Generate Go Coverage Badge
      uses: zgosalvez/go-test-coverage@v2
        with:
          badge: true

    - name: Push the Badge to the Repository
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
        git add coverage.svg
        git commit -m "chore: Update test coverage badge" || echo "No changes to commit"
        git push