name: Go Coverage Badge

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25.0

    - name: Install dependencies
      run: go mod download

    - name: Run Tests and generate coverage report
      run: go test ./internal/cli ./menu ./task -coverprofile=./cover.out -covermode=atomic -coverpkg=./internal/cli,./menu,./task

    - name: check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        config: ./.testcoverage.yml
        git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
        git-branch: badges